#line 2 "gen-scanner.c"

#line 4 "gen-scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE metac_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE metac_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via metac_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void metac_restart (FILE *input_file ,yyscan_t yyscanner );
void metac__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE metac__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void metac__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void metac__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void metac_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void metac_pop_buffer_state (yyscan_t yyscanner );

static void metac_ensure_buffer_stack (yyscan_t yyscanner );
static void metac__load_buffer_state (yyscan_t yyscanner );
static void metac__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER metac__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE metac__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE metac__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE metac__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *metac_alloc (yy_size_t ,yyscan_t yyscanner );
void *metac_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void metac_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer metac__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        metac_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            metac__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        metac_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            metac__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define metac_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[365] =
    {   0,
        0,    0,  116,  114,  113,  113,  101,  114,  107,  100,
      114,   95,   96,  105,  104,   92,  103,   99,  106,   54,
       55,   93,   89,  108,   94,  109,  112,   52,   52,   97,
       98,  110,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   90,  111,
       91,  102,   88,    0,   66,    0,   74,   91,   83,   75,
        0,    0,   72,   80,   70,   81,   71,   82,    0,   58,
        2,    1,   73,   59,   54,    0,    0,    0,   54,   54,
        0,   54,   55,   55,   55,   55,   98,   90,   97,   79,
       85,   87,   86,   78,   52,    0,    0,   76,   52,   52,

       52,   52,   52,   52,   52,   13,   52,   52,   52,   52,
       52,   52,   52,   52,   24,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   77,   84,
       56,   67,    0,   58,    1,   58,    0,   59,    0,    0,
        0,   57,   54,   54,   54,   54,    0,   53,   55,   55,
       55,   55,   69,   68,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       21,   52,   52,   26,   52,   52,   29,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   41,   52,

       52,   52,   52,   52,   52,   49,   52,   52,    0,   58,
        0,   58,    0,   59,   64,   65,    0,   57,   54,   61,
       62,   53,    0,   53,   53,   55,    3,   52,    5,   52,
        7,   52,   52,   52,   52,   52,   52,   15,   16,   52,
       52,   52,   52,   52,   23,   52,   52,   28,   30,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   40,   52,
       52,   45,   52,   52,   52,   50,   52,    0,   58,   64,
        0,   64,   65,    0,    0,   63,   61,    0,   61,   62,
        0,   53,   53,    0,   60,   53,   53,    4,    6,    8,
        9,   52,   52,   52,   52,   52,   18,   52,   20,   52,

       52,   52,   52,   52,   52,   34,   52,   52,   52,   52,
       39,   52,   52,   44,   46,   48,   52,   51,    0,   64,
       64,    0,    0,   65,   63,    0,   61,   61,    0,    0,
       62,   60,   53,   52,   52,   12,   14,   17,   52,   52,
       25,   27,   52,   33,   31,   35,   36,   37,   38,   52,
       43,   47,    0,   64,    0,   61,   52,   11,   19,   22,
       32,   42,   10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   33,
       31,   31,   31,   31,   34,   31,   31,   35,   31,   31,
       36,   37,   38,   39,   31,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   31,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        6,    7,    7,    6,    6,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    7,
        6,    6,    6,    7,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[372] =
    {   0,
        0,    0,  694,  695,  695,  695,  669,   63,   45,   64,
      655,  695,  695,  667,   60,  695,   61,   59,   71,   86,
      133,  665,  695,   75,  665,   65,  695,    0,   75,  695,
      695,  664,   38,   69,   58,   73,   89,  634,   65,   54,
       68,   73,  642,   98,   94,  118,  119,  638,  695,   68,
      695,  695,  695,  103,  695,    0,  695,  695,  695,  695,
      124,  676,  695,  695,  695,  695,  695,  695,  668,  167,
      695,    0,  695,  175,  141,  209,  163,  196,  189,  125,
      667,  172,    0,  199,  139,  184,  695,  695,  695,  657,
      695,  695,  695,  656,    0,  195,  642,  695,  625,  633,

      107,  636,  635,  622,   93,  615,  616,  613,  613,  619,
      616,  614,  611,  608,    0,  186,  613,  611,  602,  611,
      612,  618,  601,  604,  593,  133,  607,  599,  177,  599,
      605,  599,  597,  601,  601,  592,  598,  597,  695,  695,
      695,  695,  232,  695,    0,  241,  260,  695,  223,  248,
      270,  275,   39,  695,  612,  593,    0,  281,  145,  695,
      609,  582,  695,  695,  573,  582,  571,  570,  556,  554,
      198,  569,  563,  565,  561,  553,  559,  546,  561,  560,
      555,  545,  549,    0,  555,  548,    0,  542,  532,  539,
      530,  532,  542,  521,  519,  514,  516,  524,    0,  523,

      525,  506,  510,  502,  493,    0,  483,  468,  280,  291,
      310,  695,  299,  325,  329,  335,  374,  695,  695,  300,
      345,  306,  384,  232,  326,  695,    0,  468,    0,  458,
        0,  443,  413,  419,  408,  404,  406,    0,    0,  400,
      410,  402,  386,  387,    0,  374,  382,    0,    0,  383,
      366,  345,  340,  337,  339,  340,  339,  313,    0,  305,
      317,    0,  325,  317,  311,    0,  319,  388,  392,  695,
      401,  399,  695,  416,  421,  428,  695,  445,  418,  695,
      457,  211,  695,  462,  466,  324,  301,    0,    0,    0,
        0,  297,  287,  290,  282,  260,    0,  256,    0,  262,

      259,  261,  227,  241,  224,    0,  230,  226,  210,  215,
        0,  212,  203,    0,    0,    0,  180,    0,  470,  474,
      695,  483,  490,  495,  695,  503,  511,  695,  530,  515,
      534,  695,  695,  151,  144,    0,    0,    0,  136,  143,
        0,    0,  110,    0,    0,    0,    0,    0,    0,   90,
        0,    0,  519,  540,  556,  563,   80,    0,    0,    0,
        0,    0,    0,  695,  613,  620,  623,  630,  634,  108,
      635
    } ;

static yyconst flex_int16_t yy_def[372] =
    {   0,
      364,    1,  364,  364,  364,  364,  364,  365,  364,  364,
      366,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  367,  367,  364,
      364,  364,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  364,  364,
      364,  364,  364,  365,  364,  365,  364,  364,  364,  364,
      366,  366,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  368,  364,  364,   20,  364,  364,  364,  364,  364,
      369,  364,   21,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  367,  365,  366,  364,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  364,  364,
      364,  364,  364,  364,  368,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  370,  369,  364,  364,
      364,  364,  364,  364,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  370,
      371,  364,  364,  364,  364,  364,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  371,  364,
      364,  364,  364,  364,  364,  364,  364,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  364,  364,  364,  364,  367,  367,  367,  367,
      367,  367,  367,    0,  364,  364,  364,  364,  364,  364,
      364
    } ;

static yyconst flex_int16_t yy_nxt[763] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   29,   28,   28,   28,   30,    4,   31,   32,   28,
       33,   34,   35,   36,   37,   38,   28,   39,   28,   40,
       28,   41,   28,   42,   43,   44,   45,   46,   47,   48,
       28,   28,   28,   49,   50,   51,   52,   55,   57,   58,
       59,   64,  154,   69,   66,   70,   70,   70,   70,   96,
       88,   71,   97,   65,   67,   68,   72,   60,   93,   94,
       99,  139,  100,  117,   73,   89,  154,   90,   91,   56,

       74,  105,   75,   75,   75,   76,  118,   55,  101,  115,
      106,  119,  220,   77,   78,  102,  116,   79,  103,   80,
       81,  104,  107,  363,  108,  120,   77,  121,  110,   78,
      122,  141,  140,  109,  362,   82,  111,  172,  112,   56,
      128,  113,  173,   80,  124,  125,   81,   74,  129,   83,
       83,   83,   83,  361,  126,  130,  155,  127,  136,  131,
       62,   78,  167,  168,   84,  132,   85,  133,  364,  134,
      161,  137,  194,  135,  156,  364,   78,  149,  160,  150,
      150,  364,   86,   70,   70,   70,   70,  195,  162,  360,
       85,  146,  146,  146,  146,  143,  144,  359,  144,   55,

      358,  364,  160,  147,  148,  154,  148,  151,  357,  151,
      143,  144,  152,  152,  152,  152,  144,  160,  147,  148,
      153,  153,  154,   74,  148,   76,   76,   76,   76,  154,
      159,   56,  160,  159,  198,  183,  352,   78,  199,  215,
      215,  160,  184,  209,  283,  209,  154,  351,  210,  210,
      210,  210,   78,  233,  234,  350,  160,  146,  146,  146,
      146,  349,  216,  286,  150,  150,  348,  347,  283,  211,
      212,  213,  212,  213,  346,  345,  214,  214,  214,  214,
      217,  287,  344,  343,  211,  212,  152,  152,  152,  152,
      212,  152,  152,  152,  152,  221,  210,  210,  210,  210,

      342,  217,  341,  340,  218,  339,  218,  210,  210,  210,
      210,  338,  222,  223,  224,  214,  214,  214,  214,  218,
      144,  268,  144,  268,  218,  337,  269,  269,  269,  269,
      225,  277,  278,  336,  223,  144,  335,  282,  224,  283,
      144,  214,  214,  214,  214,  215,  215,  312,  334,  277,
      333,  272,  272,  278,  148,  333,  148,  313,  270,  283,
      270,  271,  318,  283,  273,  317,  273,  274,  316,  148,
      315,  314,  311,  270,  148,  282,  280,  281,  270,  273,
      310,  309,  271,  283,  273,  275,  308,  275,  274,  307,
      276,  276,  276,  276,  280,  284,  306,  284,  281,  305,

      285,  285,  285,  285,  269,  269,  269,  269,  269,  269,
      269,  269,  319,  304,  319,  272,  272,  320,  320,  320,
      320,  212,  303,  212,  302,  301,  300,  323,  321,  323,
      321,  322,  324,  324,  324,  324,  212,  276,  276,  276,
      276,  212,  299,  321,  276,  276,  276,  276,  321,  328,
      329,  298,  322,  297,  296,  295,  326,  325,  326,  325,
      294,  327,  327,  327,  327,  293,  292,  328,  330,  291,
      330,  329,  325,  331,  331,  331,  331,  325,  285,  285,
      285,  285,  285,  285,  285,  285,  320,  320,  320,  320,
      320,  320,  320,  320,  353,  332,  353,  332,  290,  354,

      354,  354,  354,  270,  289,  270,  324,  324,  324,  324,
      332,  324,  324,  324,  324,  332,  288,  267,  270,  327,
      327,  327,  327,  270,  273,  266,  273,  327,  327,  327,
      327,  331,  331,  331,  331,  354,  354,  354,  354,  273,
      277,  355,  277,  355,  273,  265,  356,  356,  356,  356,
      331,  331,  331,  331,  264,  277,  354,  354,  354,  354,
      277,  263,  262,  280,  261,  280,  260,  259,  258,  321,
      257,  321,  356,  356,  356,  356,  256,  255,  280,  356,
      356,  356,  356,  280,  321,  254,  253,  252,  251,  321,
      250,  249,  328,  248,  328,  247,  246,  245,  244,  243,

      242,  241,  240,  239,  238,  237,  236,  328,  235,  232,
      231,  230,  328,   54,  229,   54,   54,   54,   54,   54,
       61,  228,  227,   61,   61,   61,   61,   95,   95,   95,
      145,  226,  145,  145,  145,  145,  145,  158,  158,  279,
      226,  279,  219,  219,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  197,  196,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  171,  170,  169,  166,  165,   62,  164,
      163,  157,  142,   61,  138,  123,  114,   98,   92,   87,
       63,   62,   53,  364,    3,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364
    } ;

static yyconst flex_int16_t yy_chk[763] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    9,    9,
       10,   15,  153,   18,   17,   18,   18,   18,   18,   29,
       24,   19,   29,   15,   17,   17,   19,   10,   26,   26,
       33,   50,   33,   40,   19,   24,  153,   24,   24,    8,

       20,   35,   20,   20,   20,   20,   40,   54,   34,   39,
       35,   41,  370,   20,   20,   34,   39,   20,   34,   20,
       20,   34,   36,  357,   36,   41,   20,   42,   37,   20,
       42,   61,   50,   36,  350,   20,   37,  105,   37,   54,
       45,   37,  105,   20,   44,   44,   20,   21,   45,   21,
       21,   21,   21,  343,   44,   45,   80,   44,   47,   46,
       61,   21,  101,  101,   21,   46,   21,   46,   75,   46,
       85,   47,  126,   46,   80,   75,   21,   77,  159,   77,
       77,   75,   21,   70,   70,   70,   70,  126,   85,  340,
       21,   74,   74,   74,   74,   70,   70,  339,   70,   96,

      335,   75,  159,   74,   74,   82,   74,   78,  334,   78,
       70,   70,   78,   78,   78,   78,   70,   86,   74,   74,
       79,   82,   79,   76,   74,   76,   76,   76,   76,   82,
       84,   96,   84,   86,  129,  116,  317,   76,  129,  149,
      149,   86,  116,  143,  282,  143,   79,  313,  143,  143,
      143,  143,   76,  171,  171,  312,   84,  146,  146,  146,
      146,  310,  150,  224,  150,  150,  309,  308,  282,  146,
      146,  147,  146,  147,  307,  305,  147,  147,  147,  147,
      150,  224,  304,  303,  146,  146,  151,  151,  151,  151,
      146,  152,  152,  152,  152,  158,  209,  209,  209,  209,

      302,  150,  301,  300,  152,  298,  152,  210,  210,  210,
      210,  296,  158,  158,  158,  213,  213,  213,  213,  152,
      210,  211,  210,  211,  152,  295,  211,  211,  211,  211,
      158,  220,  220,  294,  158,  210,  293,  222,  158,  222,
      210,  214,  214,  214,  214,  215,  215,  260,  292,  220,
      287,  216,  216,  220,  214,  286,  214,  260,  215,  225,
      215,  215,  267,  222,  216,  265,  216,  216,  264,  214,
      263,  261,  258,  215,  214,  225,  221,  221,  215,  216,
      257,  256,  215,  225,  216,  217,  255,  217,  216,  254,
      217,  217,  217,  217,  221,  223,  253,  223,  221,  252,

      223,  223,  223,  223,  268,  268,  268,  268,  269,  269,
      269,  269,  271,  251,  271,  272,  272,  271,  271,  271,
      271,  269,  250,  269,  247,  246,  244,  274,  272,  274,
      272,  272,  274,  274,  274,  274,  269,  275,  275,  275,
      275,  269,  243,  272,  276,  276,  276,  276,  272,  279,
      279,  242,  272,  241,  240,  237,  278,  276,  278,  276,
      236,  278,  278,  278,  278,  235,  234,  279,  281,  233,
      281,  279,  276,  281,  281,  281,  281,  276,  284,  284,
      284,  284,  285,  285,  285,  285,  319,  319,  319,  319,
      320,  320,  320,  320,  322,  285,  322,  285,  232,  322,

      322,  322,  322,  320,  230,  320,  323,  323,  323,  323,
      285,  324,  324,  324,  324,  285,  228,  208,  320,  326,
      326,  326,  326,  320,  324,  207,  324,  327,  327,  327,
      327,  330,  330,  330,  330,  353,  353,  353,  353,  324,
      327,  329,  327,  329,  324,  205,  329,  329,  329,  329,
      331,  331,  331,  331,  204,  327,  354,  354,  354,  354,
      327,  203,  202,  331,  201,  331,  200,  198,  197,  354,
      196,  354,  355,  355,  355,  355,  195,  194,  331,  356,
      356,  356,  356,  331,  354,  193,  192,  191,  190,  354,
      189,  188,  356,  186,  356,  185,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  356,  172,  170,
      169,  168,  356,  365,  167,  365,  365,  365,  365,  365,
      366,  166,  165,  366,  366,  366,  366,  367,  367,  367,
      368,  162,  368,  368,  368,  368,  368,  369,  369,  371,
      161,  371,  156,  155,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  128,  127,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  104,  103,  102,  100,   99,   97,   94,
       90,   81,   69,   62,   48,   43,   38,   32,   25,   22,
       14,   11,    7,    3,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[116] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "metac-scanner.l"
/*
 * Copyright (c) 2012 Matthew Brush <mbrush@codebrainz.ca>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#line 45 "metac-scanner.l"

#include "parser.h"

#define YY_EXTRA_TYPE MetaCParser*
#define YY_USER_ACTION yylloc->first_line = yylineno;

static void comment(yyscan_t yyscanner);
static long hex_to_long(const char *);

#define MCINC {}
#line 782 "gen-scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int metac_lex_init (yyscan_t* scanner);

int metac_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int metac_lex_destroy (yyscan_t yyscanner );

int metac_get_debug (yyscan_t yyscanner );

void metac_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE metac_get_extra (yyscan_t yyscanner );

void metac_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *metac_get_in (yyscan_t yyscanner );

void metac_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *metac_get_out (yyscan_t yyscanner );

void metac_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t metac_get_leng (yyscan_t yyscanner );

char *metac_get_text (yyscan_t yyscanner );

int metac_get_lineno (yyscan_t yyscanner );

void metac_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * metac_get_lval (yyscan_t yyscanner );

void metac_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *metac_get_lloc (yyscan_t yyscanner );
    
        void metac_set_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int metac_wrap (yyscan_t yyscanner );
#else
extern int metac_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int metac_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int metac_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 57 "metac-scanner.l"


#line 1024 "gen-scanner.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			metac_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				metac__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		metac__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 365 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 695 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "metac-scanner.l"
{ MCINC; /* consume C++-style comments */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "metac-scanner.l"
{ MCINC; comment(yyscanner); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "metac-scanner.l"
{ MCINC; return MCTOK_BOOL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "metac-scanner.l"
{ MCINC; return MCTOK_BREAK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "metac-scanner.l"
{ MCINC; return MCTOK_CASE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "metac-scanner.l"
{ MCINC; return MCTOK_CATCH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "metac-scanner.l"
{ MCINC; return MCTOK_CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "metac-scanner.l"
{ MCINC; return MCTOK_CLASS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "metac-scanner.l"
{ MCINC; return MCTOK_CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "metac-scanner.l"
{ MCINC; return MCTOK_CONTINUE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "metac-scanner.l"
{ MCINC; return MCTOK_DEFAULT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "metac-scanner.l"
{ MCINC; return MCTOK_DELETE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "metac-scanner.l"
{ MCINC; return MCTOK_DO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "metac-scanner.l"
{ MCINC; return MCTOK_DOUBLE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "metac-scanner.l"
{ MCINC; return MCTOK_ELSE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "metac-scanner.l"
{ MCINC; return MCTOK_ENUM; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "metac-scanner.l"
{ MCINC; return MCTOK_EXTERN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "metac-scanner.l"
{ MCINC; return MCTOK_FALSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "metac-scanner.l"
{ MCINC; return MCTOK_FINALLY; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "metac-scanner.l"
{ MCINC; return MCTOK_FLOAT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "metac-scanner.l"
{ MCINC; return MCTOK_FOR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "metac-scanner.l"
{ MCINC; return MCTOK_FOREACH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "metac-scanner.l"
{ MCINC; return MCTOK_GOTO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "metac-scanner.l"
{ MCINC; return MCTOK_IF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "metac-scanner.l"
{ MCINC; return MCTOK_INLINE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "metac-scanner.l"
{ MCINC; return MCTOK_INT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "metac-scanner.l"
{ MCINC; return MCTOK_LAMBDA; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "metac-scanner.l"
{ MCINC; return MCTOK_LONG; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "metac-scanner.l"
{ MCINC; return MCTOK_NEW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "metac-scanner.l"
{ MCINC; return MCTOK_NULL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "metac-scanner.l"
{ MCINC; return MCTOK_RETURN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "metac-scanner.l"
{ MCINC; return MCTOK_PRIVATE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "metac-scanner.l"
{ MCINC; return MCTOK_PUBLIC; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "metac-scanner.l"
{ MCINC; return MCTOK_SHORT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "metac-scanner.l"
{ MCINC; return MCTOK_SIZEOF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "metac-scanner.l"
{ MCINC; return MCTOK_STATIC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "metac-scanner.l"
{ MCINC; return MCTOK_STRUCT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "metac-scanner.l"
{ MCINC; return MCTOK_SWITCH; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "metac-scanner.l"
{ MCINC; return MCTOK_THROW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "metac-scanner.l"
{ MCINC; return MCTOK_TRUE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "metac-scanner.l"
{ MCINC; return MCTOK_TRY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "metac-scanner.l"
{ MCINC; return MCTOK_TYPEDEF; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "metac-scanner.l"
{ MCINC; return MCTOK_TYPEOF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "metac-scanner.l"
{ MCINC; return MCTOK_UCHAR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "metac-scanner.l"
{ MCINC; return MCTOK_UINT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "metac-scanner.l"
{ MCINC; return MCTOK_ULONG; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "metac-scanner.l"
{ MCINC; return MCTOK_USHORT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "metac-scanner.l"
{ MCINC; return MCTOK_UNION; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "metac-scanner.l"
{ MCINC; return MCTOK_VAR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "metac-scanner.l"
{ MCINC; return MCTOK_VOID; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "metac-scanner.l"
{ MCINC; return MCTOK_WHILE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "metac-scanner.l"
{ MCINC;
                strncpy(yylval->mc_string, yytext, yyleng);
                return MCTOK_IDENTIFIER; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 116 "metac-scanner.l"
{ MCINC; 
                             yylval->mc_long = hex_to_long(yytext);
                             return(MCTOK_CONSTANT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 126 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 127 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 128 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 129 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 130 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 131 "metac-scanner.l"
{ MCINC; return(MCTOK_CONSTANT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "metac-scanner.l"
{ MCINC; return(MCTOK_STRING_LITERAL); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "metac-scanner.l"
{ MCINC; return MCTOK_ELLIPSIS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "metac-scanner.l"
{ MCINC; return MCTOK_RIGHT_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "metac-scanner.l"
{ MCINC; return MCTOK_LEFT_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "metac-scanner.l"
{ MCINC; return MCTOK_ADD_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 139 "metac-scanner.l"
{ MCINC; return MCTOK_SUB_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "metac-scanner.l"
{ MCINC; return MCTOK_MUL_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "metac-scanner.l"
{ MCINC; return MCTOK_DIV_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 142 "metac-scanner.l"
{ MCINC; return MCTOK_MOD_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "metac-scanner.l"
{ MCINC; return MCTOK_AND_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 144 "metac-scanner.l"
{ MCINC; return MCTOK_XOR_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 145 "metac-scanner.l"
{ MCINC; return MCTOK_OR_ASSIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 146 "metac-scanner.l"
{ MCINC; return MCTOK_RIGHT_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 147 "metac-scanner.l"
{ MCINC; return MCTOK_LEFT_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 148 "metac-scanner.l"
{ MCINC; return MCTOK_INC_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 149 "metac-scanner.l"
{ MCINC; return MCTOK_DEC_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "metac-scanner.l"
{ MCINC; return MCTOK_PTR_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "metac-scanner.l"
{ MCINC; return MCTOK_AND_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "metac-scanner.l"
{ MCINC; return MCTOK_OR_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "metac-scanner.l"
{ MCINC; return MCTOK_LE_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "metac-scanner.l"
{ MCINC; return MCTOK_GE_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "metac-scanner.l"
{ MCINC; return MCTOK_EQ_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "metac-scanner.l"
{ MCINC; return MCTOK_NE_OP; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "metac-scanner.l"
{ MCINC; return(';'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "metac-scanner.l"
{ MCINC; return('{'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "metac-scanner.l"
{ MCINC; return('}'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 160 "metac-scanner.l"
{ MCINC; return(','); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 161 "metac-scanner.l"
{ MCINC; return(':'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 162 "metac-scanner.l"
{ MCINC; return('='); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 163 "metac-scanner.l"
{ MCINC; return('('); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 164 "metac-scanner.l"
{ MCINC; return(')'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 165 "metac-scanner.l"
{ MCINC; return('['); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 166 "metac-scanner.l"
{ MCINC; return(']'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 167 "metac-scanner.l"
{ MCINC; return('.'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 168 "metac-scanner.l"
{ MCINC; return('&'); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 169 "metac-scanner.l"
{ MCINC; return('!'); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 170 "metac-scanner.l"
{ MCINC; return('~'); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "metac-scanner.l"
{ MCINC; return('-'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 172 "metac-scanner.l"
{ MCINC; return('+'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 173 "metac-scanner.l"
{ MCINC; return('*'); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 174 "metac-scanner.l"
{ MCINC; return('/'); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 175 "metac-scanner.l"
{ MCINC; return('%'); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 176 "metac-scanner.l"
{ MCINC; return('<'); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 177 "metac-scanner.l"
{ MCINC; return('>'); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 178 "metac-scanner.l"
{ MCINC; return('^'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 179 "metac-scanner.l"
{ MCINC; return('|'); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 180 "metac-scanner.l"
{ MCINC; return('?'); }
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 182 "metac-scanner.l"
{ MCINC; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 183 "metac-scanner.l"
{ /* todo: add code to complain about unmatched characters */ }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 185 "metac-scanner.l"
ECHO;
	YY_BREAK
#line 1703 "gen-scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * metac_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( metac_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of metac_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					metac_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			metac_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) metac_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 365 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 365 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 364);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					metac_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( metac_wrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void metac_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        metac_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            metac__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	metac__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	metac__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void metac__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		metac_pop_buffer_state();
	 *		metac_push_buffer_state(new_buffer);
     */
	metac_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	metac__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (metac_wrap()) processing, but the only time this flag
	 * is looked at is after metac_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void metac__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE metac__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) metac_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in metac__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) metac_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in metac__create_buffer()" );

	b->yy_is_our_buffer = 1;

	metac__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with metac__create_buffer()
 * @param yyscanner The scanner object.
 */
    void metac__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		metac_free((void *) b->yy_ch_buf ,yyscanner );

	metac_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a metac_restart() or at EOF.
 */
    static void metac__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	metac__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then metac__init_buffer was _probably_
     * called from metac_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void metac__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		metac__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void metac_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	metac_ensure_buffer_stack(yyscanner);

	/* This block is copied from metac__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from metac__switch_to_buffer. */
	metac__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void metac_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	metac__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		metac__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void metac_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)metac_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in metac_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)metac_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in metac_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE metac__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) metac_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in metac__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	metac__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to metac_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       metac__scan_bytes() instead.
 */
YY_BUFFER_STATE metac__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return metac__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to metac_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE metac__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) metac_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in metac__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = metac__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in metac__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE metac_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int metac_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int metac_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *metac_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *metac_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t metac_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *metac_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void metac_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void metac_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "metac_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void metac_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "metac_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see metac__switch_to_buffer
 */
void metac_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void metac_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int metac_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void metac_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * metac_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void metac_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *metac_get_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void metac_set_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* metac_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int metac_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) metac_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* metac_lex_init_extra has the same functionality as metac_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to metac_alloc in
 * the yyextra field.
 */

int metac_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    metac_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) metac_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    metac_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from metac_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * metac_lex_init()
     */
    return 0;
}

/* metac_lex_destroy is for both reentrant and non-reentrant scanners. */
int metac_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		metac__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		metac_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	metac_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        metac_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * metac_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    metac_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *metac_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *metac_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void metac_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see metac_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 185 "metac-scanner.l"



static long hex_to_long(const char *s)
{
  long l;
  errno = 0;
  l = strtol(s, NULL, 16);
  if (errno == 0) {
    return l;
  }
  metac_error("failed to convert hex to long\n");
}

static void comment(yyscan_t yyscanner)
{
  int c, prev = 0;

  while ((c = input(yyscanner)) != 0) {

    if (prev == '*' && c == '/') {
      return;
    }

    prev = c;
  }
  metac_error("unterminated comment");
}

